### ISSUE TITLE
task fails due to webpagetest.org running under SSL

### ISSUE THREAD

**Issue by boneyfantaseas** [tkadlec/grunt-perfbudget#34]
Hey,
I'm experiencing 301 redirect messages for some weeks now. First I wondered whether my local credentials or redirects would be wrong but it turned out that inside the plugin all calls to webpagetest.org are made with HTTP calls. As the domain is delivered via SSL I changed all occurences in /lib to https and it worked again. So maybe you want to have a look into it?

**Comment by tkadlec** [comment]
Thanks! Changed the default to use https and we should be good to go. :)
